export const CUSTOM_IGNORE_FILENAME = '.snipkitignore';
export const DEFAULT_IGNORE_PATTERNS = [
  '**/node_modules/**',
  '**/git/**',
  '**/next/**',
  '**/turbo/**',
  '**/vercel/**',
  '**/dist/**',
  '**/build/**',
  '**/coverage/**',
  '**/cache/**',
  '*.log',
  '*.DS_Store',
  '**/idea/**',
  '**/vscode/**',
  '**/__pycache__/**',
  '*.pyc',
  '**/venv/**',
  '**/venv/**',
  '**/env/**',
  '*.svg',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.m4a',
  '*.mps',
  '**/pytest_cache/**',
  '**/terraform/**',
  '**/target/**',
  '**/vendor/**',
  '**/cargo/**',
  '**/gradle/**',
  '**/mvn/**',
  '*.class',
  '*.swp',
  '*.iml',
];
export const DEFAULT_PAGE_SIZE = 9;
export const TAB_REFETCH_TIME = 5 * 60 * 1000;
